### PR TITLE
adds initial project structure

### PR DESCRIPTION
**Pull request by nkristek**
This PR shows my suggestion for a project structure which supports the multi library approach we talked about. As seen in the `Package.swift` file there are 3 libraries:
- **RSocketCore**: Has no dependencies and contains only parsing logic. Maybe it needs `SwiftNIO` for `ByteBuffer` (depending on which path we want to take regarding `Data` vs. `ByteBuffer`)
- **RSocketCombine**: Has a dependency on `RSocketCore` to access the parsing logic and implements `Combine` publishers
- **RSocketReactiveSwift**: Has a dependency on `RSocketCore` to access the parsing logic and `ReactiveSwift` to implement it using `SignalProducer`

The example project is not part of this PR as we should focus on the main library first.

### CODE REVIEW

**Comment by OlegDokuka** [comment]
I like this approach.

I would suggest keeping naming the same between all the projects, hence I would suggest renaming RSocket to RSocketCore.

Apart, so far soo good

**Comment by Marcocanc** [comment]
I like this as well!

**Comment by ciychodianda** [comment]
I like this approach. This covers the core and API portions. How do we want to handle the transport?
Transports/RSocketSwiftNIO/RSocketSwiftNIO-Client/
OR
RSocket-Transport-SwiftNIO/RSocket-Transport-SwiftNIO-Client

**Comment by OlegDokuka** [comment]
I'm for the `RSocket-Transport-SwiftNIO/RSocket-Transport-SwiftNIO-Client` to keep the convention between implementations. Or even `RSocket-Transport-SwiftNIO-Client` and `RSocket-Transport-SwiftNIO-Server`

**Comment by OlegDokuka** [comment]
@nkristek moving PR to `Ready for review`. Please make sure your commits are signed to pass the DCO check

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Review by ciychodianda — APPROVED** [review]
LGTM

**Review by Marcocanc — APPROVED** [review]

**Review by Samer-Abdulaziz — APPROVED** [review]
Looks good

**Pull request merged**
